# Generated by Django 4.2.6 on 2024-06-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialzation',
            new_name='specialization',
        ),
    ]
