# Generated by Django 5.0.7 on 2024-07-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_rename_specialzation_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
