# Generated by Django 5.0.7 on 2024-07-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_patient_balance_patient_discharge_patient_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
